site:
  name: OpenFav
  site: 'https://open-favs.vercel.app'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: orcPxI47GSa-cRvY11tUe6iGg2IO_RPvnA1q95iEM3M

# Default SEO metadata
metadata:
  title:
    default: Openfav
    template: '%s — Openfav'
  description: "Welcome in the productivity platform for developers, easily manage resources and productivity"
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Openfav
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@onwidget'
    site: '@onwidget'
    cardType: summary_large_image
